tournament:
  name: "aug_wdl_100"
  max_nodes: 100
  rounds: 1000
  batch_size: 64
  cards: standard

models:
  resnet_aug:
    config: "resnet_aug.yaml"
    start_gen: 100
    end_gen: 100
    step_gen: 1
    
  resnet_aug_wdl: 
    config: "resnet_aug_wdl.yaml"
    start_gen: 100
    end_gen: 100
    step_gen: 1