tournament:
  name: "aug_mask_0.yaml"
  max_nodes: 2
  rounds: 1000
  batch_size: 64
  cards: standard

models:
  resnet_aug:
    config: "resnet_aug.yaml"
    start_gen: 100
    end_gen: 100
    step_gen: 1
    
  resnet_aug_mask: 
    config: "resnet_aug_mask.yaml"
    start_gen: 100
    end_gen: 100
    step_gen: 1