tournament:
  name: "mask_100.yaml"
  max_nodes: 100
  rounds: 500
  batch_size: 64
  cards: standard

models:
  resnet:
    config: "resnet.yaml"
    start_gen: 100
    end_gen: 100
    step_gen: 1
    
  resnet_mask: 
    config: "resnet_mask.yaml"
    start_gen: 100
    end_gen: 100
    step_gen: 1