tournament:
  name: "standard_cards"
  max_nodes: 200
  rounds: 200
  batch_size: 64
  cards: standard

models:
  resnet_6_96: 
    config: "resnet_6_96.yaml"
    start_gen: 12
    end_gen: 12
    step_gen: 1

  shallow_se_net_6_96:
    config: "shallow_se_net_6_96.yaml"
    start_gen: 20
    end_gen: 20
    step_gen: 1

  