tournament:
  name: "standard_cards"
  max_nodes: 100
  rounds: 60
  batch_size: 64
  cards: standard

models:
  resnet_6_96: 
    config: "resnet_6_96.yaml"
    start_gen: 12
    end_gen: 12
    step_gen: 1

  se_net_6_96:
    config: "se_net_6_96.yaml"
    start_gen: 0
    end_gen: 0
    step_gen: 1
  