tournament:
  name: "wdl"
  max_nodes: 400
  rounds: 500
  batch_size: 64
  cards: standard

models:
  se_net_6_96: 
    config: "se_net_6_96.yaml"
    start_gen: 12
    end_gen: 12
    step_gen: 1

  se_net_6_96_wdl:
    config: "se_net_6_96_wdl.yaml"
    start_gen: 12
    end_gen: 12
    step_gen: 1